class CartPageLocators:
    item_at_cart_name = '//*[@id="item_4_title_link"]/div'
    remove_button = '//*[@id="remove-sauce-labs-backpack"]'
    continue_shopping_button = '//*[@id="continue-shopping"]'
    checkout_button = '//*[@id="checkout"]'
    first_name_textfield = '//*[@id="first-name"]'
    last_name_textfield = '//*[@id="last-name"]'
    zip_textfield = '//*[@id="postal-code"]'
    continue_button = '//*[@id="continue"]'
    checkout_information_label = '//*[@id="header_container"]/div[2]/span'
    item_price = '//*[@id="checkout_summary_container"]/div/div[2]/div[6]'
    tax_price = '//*[@id="checkout_summary_container"]/div/div[2]/div[7]'
    total_price = '//*[@id="checkout_summary_container"]/div/div[2]/div[8]'
    finish_button = '//*[@id="finish"]'
    checkout_complete_label = '//*[@id="header_container"]/div[2]/span'